version: "3.8"
services:
  db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: omhhdev
    volumes:
      - db-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: dracula

  s3-minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: accessKey1
      MINIO_SECRET_KEY: verySecretKey1
    ports:
      - 9000:9000
    command: server /data
    volumes:
      - s3-data:/data

  bootstrap-minio:
    image: amazon/aws-cli
    command: s3api --endpoint-url http://s3-minio:9000 --no-verify-ssl create-bucket --bucket omhh-images
    volumes:
      - ./.aws:/root/.aws
    depends_on:
      - s3-minio

volumes:
  s3-data:
  db-data:
